-- ========================================================
-- CodeArena Database Update Script
-- Copy-paste and run this script in your Supabase SQL Editor
-- ========================================================

-- 1. Create Question Banks table
CREATE TABLE IF NOT EXISTS public.question_banks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT,
    year TEXT NOT NULL, -- 'Second Year' or 'Third Year'
    status TEXT DEFAULT 'Active', -- 'Active' or 'Inactive'
    created_at TIMESTAMPTZ DEFAULT NOW(),
    created_by TEXT DEFAULT 'Admin'
);

-- 2. Add question_bank_id to questions table
ALTER TABLE public.questions ADD COLUMN IF NOT EXISTS question_bank_id BIGINT REFERENCES public.question_banks(id) ON DELETE SET NULL;

-- 3. Add columns to tests table
ALTER TABLE public.tests ADD COLUMN IF NOT EXISTS year TEXT DEFAULT 'Second Year';
ALTER TABLE public.tests ADD COLUMN IF NOT EXISTS question_bank_id BIGINT REFERENCES public.question_banks(id) ON DELETE SET NULL;
ALTER TABLE public.tests ADD COLUMN IF NOT EXISTS randomize_questions BOOLEAN DEFAULT FALSE;

-- 4. Add assigned_questions to test_attempts table
ALTER TABLE public.test_attempts ADD COLUMN IF NOT EXISTS assigned_questions JSONB DEFAULT '[]'::jsonb;

-- 5. Enable Row Level Security (RLS) on question_banks
ALTER TABLE public.question_banks ENABLE ROW LEVEL SECURITY;

-- 6. Create public access policy for question_banks
DROP POLICY IF EXISTS "Allow public access question_banks" ON public.question_banks;
CREATE POLICY "Allow public access question_banks" ON public.question_banks FOR ALL USING (true) WITH CHECK (true);

-- 7. Insert default August Month Question Bank for Second Year
INSERT INTO public.question_banks (id, title, description, year, status)
VALUES (1, 'August Month Question Bank', 'August Month Question Bank with 20 seeded coding challenges', 'Second Year', 'Active')
ON CONFLICT (id) DO NOTHING;

-- 8. Place all existing questions inside the August Month Question Bank
UPDATE public.questions SET question_bank_id = 1;

-- ========================================================
-- SECURITY HARDENING (OPTIONAL - read carefully)
-- ========================================================
-- The anon key in the browser is public, so "Allow public access" policies
-- on test_cases expose hidden test cases to any student who opens the browser
-- devtools and queries Supabase directly.
--
-- IMPORTANT: The admin frontend (QuestionEditor) currently reads test_cases
-- through the anon key. Run the section below ONLY after the admin flows are
-- migrated to the FastAPI backend (which stores test cases in its own database
-- and never ships hidden cases to students). Until then, keep the public
-- policy on test_cases.

-- Lock down test_cases: only a JWT with role=authenticated and custom claim
-- x-codearena-role='admin' (issued by your own auth service) may read rows.
-- ALTER TABLE public.test_cases ENABLE ROW LEVEL SECURITY;
-- DROP POLICY IF EXISTS "Allow public access test_cases" ON public.test_cases;
-- CREATE POLICY "Only admin JWTs can read test_cases" ON public.test_cases
--   FOR SELECT USING (
--     auth.jwt() ->> 'x-codearena-role' = 'admin'
--   );

-- Repeat the same pattern for the other exam tables if they should be
-- admin-only (questions, tests, users, test_attempts, submissions).
-- ALTER TABLE public.questions ENABLE ROW LEVEL SECURITY;
-- DROP POLICY IF EXISTS "Allow public access questions" ON public.questions;
-- CREATE POLICY "Only admin JWTs can read questions" ON public.questions
--   FOR SELECT USING (auth.jwt() ->> 'x-codearena-role' = 'admin');
