-- ========================================================
-- CodeArena Supabase Database Setup & Seeder Script
-- Run this script in your Supabase SQL Editor
-- ========================================================

-- 1. Create Users / Student Registration Table
CREATE TABLE IF NOT EXISTS public.users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    register_number TEXT UNIQUE NOT NULL,
    department TEXT DEFAULT 'AI & DS',
    year INT DEFAULT 1,
    section TEXT DEFAULT 'A',
    role TEXT DEFAULT 'student',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Create Questions Bank Table
CREATE TABLE IF NOT EXISTS public.questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    statement TEXT NOT NULL,
    difficulty TEXT DEFAULT 'easy',
    marks INT DEFAULT 10,
    topic TEXT DEFAULT 'General',
    input_format TEXT,
    output_format TEXT,
    sample_input TEXT,
    sample_output TEXT,
    explanation TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Create Test Cases Table
CREATE TABLE IF NOT EXISTS public.test_cases (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question_id BIGINT REFERENCES public.questions(id) ON DELETE CASCADE,
    input TEXT NOT NULL,
    expected_output TEXT NOT NULL,
    is_hidden BOOLEAN DEFAULT FALSE
);

-- 4. Create Tests / Assessments Table
CREATE TABLE IF NOT EXISTS public.tests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT,
    duration_minutes INT DEFAULT 60,
    questions_per_student INT DEFAULT 5,
    total_marks INT DEFAULT 50,
    allowed_languages JSONB DEFAULT '["python", "java", "c", "cpp"]'::jsonb,
    max_violations INT DEFAULT 3,
    start_time TIMESTAMPTZ DEFAULT NOW(),
    end_time TIMESTAMPTZ DEFAULT (NOW() + INTERVAL '7 days')
);

-- 5. Create Test Attempts Table
CREATE TABLE IF NOT EXISTS public.test_attempts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    test_id BIGINT REFERENCES public.tests(id) ON DELETE CASCADE,
    user_id BIGINT REFERENCES public.users(id) ON DELETE CASCADE,
    status TEXT DEFAULT 'in_progress',
    score INT DEFAULT 0,
    violation_count INT DEFAULT 0,
    started_at TIMESTAMPTZ DEFAULT NOW(),
    expires_at TIMESTAMPTZ DEFAULT (NOW() + INTERVAL '1 hour'),
    submitted_at TIMESTAMPTZ
);

-- 6. Create Code Submissions Log Table
CREATE TABLE IF NOT EXISTS public.submissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    attempt_id BIGINT REFERENCES public.test_attempts(id) ON DELETE CASCADE,
    question_id BIGINT REFERENCES public.questions(id) ON DELETE CASCADE,
    language TEXT DEFAULT 'python',
    code TEXT NOT NULL,
    status TEXT DEFAULT 'submitted',
    score INT DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable Row Level Security (RLS) & Public Read/Write for Assessment
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.questions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.test_cases ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tests ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.test_attempts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.submissions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public access users" ON public.users FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public access questions" ON public.questions FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public access test_cases" ON public.test_cases FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public access tests" ON public.tests FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public access test_attempts" ON public.test_attempts FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public access submissions" ON public.submissions FOR ALL USING (true) WITH CHECK (true);

-- 7. Insert Initial Seed Data for Assessment
INSERT INTO public.tests (id, name, description, duration_minutes, questions_per_student, total_marks)
VALUES (1, 'AI & DS Coding Assessment - Round 1', 'Official online assessment for AI & DS department. Complete 5 coding challenges within 60 minutes.', 60, 5, 50)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.questions (id, title, statement, difficulty, marks, topic, input_format, output_format, sample_input, sample_output, explanation)
VALUES 
(101, 'Two Sum', 'Given an array of integers `nums` and an integer `target`, return indices of the two numbers such that they add up to target.', 'easy', 10, 'Arrays', 'First line: n\nSecond line: n integers\nThird line: target', 'Two space-separated indices', '4\n2 7 11 15\n9', '0 1', 'nums[0] + nums[1] = 9'),
(102, 'Reverse String', 'Write a function that reverses a string.', 'easy', 10, 'Strings', 'Single line string', 'Reversed string', 'hello', 'olleh', 'Reverse of hello is olleh'),
(103, 'Palindrome Check', 'Determine if a string is a palindrome.', 'easy', 10, 'Strings', 'Single line string', 'true or false', 'racecar', 'true', 'racecar is a palindrome'),
(104, 'Maximum Subarray', 'Find contiguous subarray with largest sum.', 'medium', 10, 'Arrays', 'First line: n\nSecond line: n integers', 'Largest sum integer', '9\n-2 1 -3 4 -1 2 1 -5 4', '6', '[4,-1,2,1] has max sum 6'),
(105, 'Valid Parentheses', 'Determine if input string of brackets is valid.', 'easy', 10, 'Stacks', 'Single string', 'true or false', '()[]{}', 'true', 'Brackets closed correctly')
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.test_cases (question_id, input, expected_output, is_hidden)
VALUES 
(101, '4\n2 7 11 15\n9', '0 1', false),
(101, '3\n3 2 4\n6', '1 2', false),
(102, 'hello', 'olleh', false),
(102, 'world', 'dlrow', false),
(103, 'racecar', 'true', false),
(103, 'hello', 'false', false)
ON CONFLICT DO NOTHING;
