-- ========================================================
-- CodeArena Supabase Database Setup & Seeder Script
-- Run this script in your Supabase SQL Editor
-- ========================================================

-- 1. Create Users / Student Registration Table
CREATE TABLE IF NOT EXISTS public.users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    register_number TEXT UNIQUE NOT NULL,
    department TEXT DEFAULT 'AI & DS',
    year INT DEFAULT 1,
    section TEXT DEFAULT 'A',
    role TEXT DEFAULT 'student',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Create Questions Bank Table
CREATE TABLE IF NOT EXISTS public.questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    statement TEXT NOT NULL,
    difficulty TEXT DEFAULT 'easy',
    marks INT DEFAULT 10,
    topic TEXT DEFAULT 'General',
    input_format TEXT,
    output_format TEXT,
    sample_input TEXT,
    sample_output TEXT,
    explanation TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Create Test Cases Table
CREATE TABLE IF NOT EXISTS public.test_cases (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question_id BIGINT REFERENCES public.questions(id) ON DELETE CASCADE,
    input TEXT NOT NULL,
    expected_output TEXT NOT NULL,
    is_hidden BOOLEAN DEFAULT FALSE
);

-- 4. Create Tests / Assessments Table
CREATE TABLE IF NOT EXISTS public.tests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT,
    duration_minutes INT DEFAULT 60,
    questions_per_student INT DEFAULT 5,
    total_marks INT DEFAULT 50,
    allowed_languages JSONB DEFAULT '["python", "java", "c", "cpp"]'::jsonb,
    max_violations INT DEFAULT 3,
    start_time TIMESTAMPTZ DEFAULT NOW(),
    end_time TIMESTAMPTZ DEFAULT (NOW() + INTERVAL '7 days')
);

-- 5. Create Test Attempts Table
CREATE TABLE IF NOT EXISTS public.test_attempts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    test_id BIGINT REFERENCES public.tests(id) ON DELETE CASCADE,
    user_id BIGINT REFERENCES public.users(id) ON DELETE CASCADE,
    status TEXT DEFAULT 'in_progress',
    score INT DEFAULT 0,
    violation_count INT DEFAULT 0,
    started_at TIMESTAMPTZ DEFAULT NOW(),
    expires_at TIMESTAMPTZ DEFAULT (NOW() + INTERVAL '1 hour'),
    submitted_at TIMESTAMPTZ
);

-- 6. Create Code Submissions Log Table
CREATE TABLE IF NOT EXISTS public.submissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    attempt_id BIGINT REFERENCES public.test_attempts(id) ON DELETE CASCADE,
    question_id BIGINT REFERENCES public.questions(id) ON DELETE CASCADE,
    language TEXT DEFAULT 'python',
    code TEXT NOT NULL,
    status TEXT DEFAULT 'submitted',
    score INT DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable Row Level Security (RLS) & Public Read/Write for Assessment
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.questions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.test_cases ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tests ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.test_attempts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.submissions ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow public access users" ON public.users;
CREATE POLICY "Allow public access users" ON public.users FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public access questions" ON public.questions;
CREATE POLICY "Allow public access questions" ON public.questions FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public access test_cases" ON public.test_cases;
CREATE POLICY "Allow public access test_cases" ON public.test_cases FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public access tests" ON public.tests;
CREATE POLICY "Allow public access tests" ON public.tests FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public access test_attempts" ON public.test_attempts;
CREATE POLICY "Allow public access test_attempts" ON public.test_attempts FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public access submissions" ON public.submissions;
CREATE POLICY "Allow public access submissions" ON public.submissions FOR ALL USING (true) WITH CHECK (true);

-- 7. Insert Initial Seed Data for Assessment
INSERT INTO public.tests (id, name, description, duration_minutes, questions_per_student, total_marks)
VALUES (1, 'AI & DS Coding Assessment - Round 1', 'Official online assessment for AI & DS department. Complete 1 coding challenge within 60 minutes.', 60, 1, 50)
ON CONFLICT (id) DO UPDATE SET questions_per_student = 1, total_marks = 50;

INSERT INTO public.questions (id, title, statement, difficulty, marks, topic, input_format, output_format, sample_input, sample_output, explanation)
VALUES 
(101, 'Two Sum', 'Given an array of integers `nums` and an integer `target`, return indices of the two numbers such that they add up to target.', 'easy', 50, 'Arrays', 'First line: n\nSecond line: n integers\nThird line: target', 'Two space-separated indices', '4\n2 7 11 15\n9', '0 1', 'nums[0] + nums[1] = 9'),
(102, 'Reverse String', 'Write a function that reverses a string.', 'easy', 50, 'Strings', 'Single line string', 'Reversed string', 'hello', 'olleh', 'Reverse of hello is olleh'),
(103, 'Palindrome Check', 'Determine if a string is a palindrome.', 'easy', 50, 'Strings', 'Single line string', 'true or false', 'racecar', 'true', 'racecar is a palindrome'),
(104, 'Maximum Subarray', 'Find contiguous subarray with largest sum.', 'medium', 50, 'Arrays', 'First line: n\nSecond line: n integers', 'Largest sum integer', '9\n-2 1 -3 4 -1 2 1 -5 4', '6', '[4,-1,2,1] has max sum 6'),
(105, 'Valid Parentheses', 'Determine if input string of brackets is valid.', 'easy', 50, 'Stacks', 'Single string', 'true or false', '()[]{}', 'true', 'Brackets closed correctly'),
(106, 'Convert Temperature', 'Convert Celsius to Kelvin and Fahrenheit.', 'easy', 50, 'Math', 'Single float celsius', 'Two lines: Kelvin\nFahrenheit', '36.50', '309.65\n97.70', 'Celsius converted to Kelvin and Fahrenheit'),
(107, 'Power of Three', 'Given an integer n, return true if it is a power of three.', 'easy', 50, 'Math', 'Single integer n', 'true or false', '27', 'true', '27 is 3^3'),
(108, 'Sqrt(x)', 'Compute and return the square root of x rounded down.', 'easy', 50, 'Math', 'Single integer x', 'Square root integer', '8', '2', 'sqrt(8) = 2.828 -> 2'),
(109, 'Remove Duplicates from Sorted Array', 'Remove duplicates in-place from sorted array.', 'easy', 50, 'Arrays', 'First line: n\nSecond line: n integers', 'Space separated unique elements', '3\n1 1 2', '1 2', 'Unique elements are 1 and 2'),
(110, 'Roman to Integer', 'Convert Roman numeral string to integer.', 'easy', 50, 'Strings', 'Single Roman string', 'Integer', 'III', '3', 'III = 3'),
(111, 'Palindrome Number', 'Determine whether an integer is a palindrome.', 'easy', 50, 'Math', 'Single integer', 'true or false', '121', 'true', '121 reads same backward'),
(112, 'Sort Array By Parity', 'Move all even integers to beginning of array followed by odd.', 'easy', 50, 'Arrays', 'First line: n\nSecond line: n integers', 'Space separated sorted elements', '4\n3 1 2 4', '2 4 3 1', 'Even numbers first'),
(113, 'Shuffle the Array', 'Given array nums consisting of 2n elements, return array in form [x1,y1,x2,y2...].', 'easy', 50, 'Arrays', 'First line: n\nSecond line: 2n integers', 'Shuffled elements', '3\n2 5 1 3 4 7', '2 3 5 4 1 7', 'Pairs (x_i, y_i) interleaved'),
(114, 'Single Element in a Sorted Array', 'Every element appears twice except for one. Find single element.', 'medium', 50, 'Arrays', 'First line: n\nSecond line: n integers', 'Single element integer', '9\n1 1 2 3 3 4 4 8 8', '2', '2 appears once'),
(115, 'Build Array from Permutation', 'Build array ans where ans[i] = nums[nums[i]].', 'easy', 50, 'Arrays', 'First line: n\nSecond line: n integers', 'Permuted elements', '6\n0 2 1 5 3 4', '0 1 2 4 5 3', 'ans[0] = nums[nums[0]] = nums[0] = 0'),
(116, 'Element Appearing More Than 25% in a Sorted Array', 'Find integer that occurs more than 25% of the time.', 'easy', 50, 'Arrays', 'First line: n\nSecond line: n integers', 'Integer', '9\n1 2 2 6 6 6 6 7 10', '6', '6 appears 4/9 times (>25%)'),
(117, 'Search Insert Position', 'Return index if target is found or where it would be inserted.', 'easy', 50, 'Arrays', 'First line: n\nSecond line: n integers\nThird line: target', 'Index integer', '4\n1 3 5 6\n5', '2', '5 is at index 2'),
(118, 'Move Zeroes', 'Move all 0s to end while maintaining relative order of non-zero elements.', 'easy', 50, 'Arrays', 'First line: n\nSecond line: n integers', 'Space separated elements', '5\n0 1 0 3 12', '1 3 12 0 0', 'Zeroes moved to end'),
(119, 'Remove Element', 'Remove all instances of val in-place and return remaining.', 'easy', 50, 'Arrays', 'First line: n\nSecond line: n integers\nThird line: val', 'Remaining elements', '4\n3 2 2 3\n3', '2 2', '3s removed'),
(120, 'Single Number', 'Find single non-repeating element in array where others appear twice.', 'easy', 50, 'Arrays', 'First line: n\nSecond line: n integers', 'Single integer', '3\n2 2 1', '1', '1 appears once')
ON CONFLICT (id) DO UPDATE SET marks = 50;

INSERT INTO public.test_cases (question_id, input, expected_output, is_hidden)
VALUES 
-- 101: Two Sum
(101, '4\n2 7 11 15\n9', '0 1', false),
(101, '3\n3 2 4\n6', '1 2', false),
(101, '2\n3 3\n6', '0 1', true),

-- 102: Reverse String
(102, 'hello', 'olleh', false),
(102, 'world', 'dlrow', false),
(102, 'CodeArena', 'anerAedoC', true),

-- 103: Palindrome Check
(103, 'racecar', 'true', false),
(103, 'hello', 'false', false),
(103, 'madam', 'true', true),

-- 104: Maximum Subarray
(104, '9\n-2 1 -3 4 -1 2 1 -5 4', '6', false),
(104, '1\n1', '1', false),
(104, '5\n5 4 -1 7 8', '23', true),

-- 105: Valid Parentheses
(105, '()[]{}', 'true', false),
(105, '(]', 'false', false),
(105, '{[]}', 'true', true),

-- 106: Convert Temperature
(106, '36.50', '309.65\n97.70', false),
(106, '0.00', '273.15\n32.00', false),
(106, '100.00', '373.15\n212.00', true),

-- 107: Power of Three
(107, '27', 'true', false),
(107, '0', 'false', false),
(107, '9', 'true', true),

-- 108: Sqrt(x)
(108, '4', '2', false),
(108, '8', '2', false),
(108, '16', '4', true),

-- 109: Remove Duplicates from Sorted Array
(109, '3\n1 1 2', '1 2', false),
(109, '10\n0 0 1 1 1 2 2 3 3 4', '0 1 2 3 4', false),
(109, '2\n1 1', '1', true),

-- 110: Roman to Integer
(110, 'III', '3', false),
(110, 'LVIII', '58', false),
(110, 'MCMXCIV', '1994', true),

-- 111: Palindrome Number
(111, '121', 'true', false),
(111, '-121', 'false', false),
(111, '10', 'false', true),

-- 112: Sort Array By Parity
(112, '4\n3 1 2 4', '2 4 3 1', false),
(112, '1\n0', '0', false),
(112, '2\n1 2', '2 1', true),

-- 113: Shuffle the Array
(113, '3\n2 5 1 3 4 7', '2 3 5 4 1 7', false),
(113, '4\n1 2 3 4 4 3 2 1', '1 4 2 3 3 2 4 1', false),
(113, '2\n1 1 2 2', '1 2 1 2', true),

-- 114: Single Element in a Sorted Array
(114, '9\n1 1 2 3 3 4 4 8 8', '2', false),
(114, '7\n3 3 7 7 10 11 11', '10', false),
(114, '1\n1', '1', true),

-- 115: Build Array from Permutation
(115, '6\n0 2 1 5 3 4', '0 1 2 4 5 3', false),
(115, '6\n5 0 1 2 3 4', '4 5 0 1 2 3', false),
(115, '2\n1 0', '0 1', true),

-- 116: Element Appearing More Than 25% in a Sorted Array
(116, '9\n1 2 2 6 6 6 6 7 10', '6', false),
(116, '4\n1 1 2 2', '1', false),
(116, '1\n1', '1', true),

-- 117: Search Insert Position
(117, '4\n1 3 5 6\n5', '2', false),
(117, '4\n1 3 5 6\n2', '1', false),
(117, '4\n1 3 5 6\n7', '4', true),

-- 118: Move Zeroes
(118, '5\n0 1 0 3 12', '1 3 12 0 0', false),
(118, '1\n0', '0', false),
(118, '3\n2 1 0', '2 1 0', true),

-- 119: Remove Element
(119, '4\n3 2 2 3\n3', '2 2', false),
(119, '8\n0 1 2 2 3 0 4 2\n2', '0 1 3 0 4', false),
(119, '2\n1 1\n1', '', true),

-- 120: Single Number
(120, '3\n2 2 1', '1', false),
(120, '5\n4 1 2 1 2', '4', false),
(120, '1\n1', '1', true)
ON CONFLICT DO NOTHING;
