-- ========================================================
-- CodeArena Database Update Script
-- Copy-paste and run this script in your Supabase SQL Editor
-- ========================================================

-- 1. Create Question Banks table
CREATE TABLE IF NOT EXISTS public.question_banks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT,
    year TEXT NOT NULL, -- 'Second Year' or 'Third Year'
    status TEXT DEFAULT 'Active', -- 'Active' or 'Inactive'
    created_at TIMESTAMPTZ DEFAULT NOW(),
    created_by TEXT DEFAULT 'Admin'
);

-- 2. Add question_bank_id to questions table
ALTER TABLE public.questions ADD COLUMN IF NOT EXISTS question_bank_id BIGINT REFERENCES public.question_banks(id) ON DELETE SET NULL;

-- 3. Add columns to tests table
ALTER TABLE public.tests ADD COLUMN IF NOT EXISTS year TEXT DEFAULT 'Second Year';
ALTER TABLE public.tests ADD COLUMN IF NOT EXISTS question_bank_id BIGINT REFERENCES public.question_banks(id) ON DELETE SET NULL;
ALTER TABLE public.tests ADD COLUMN IF NOT EXISTS randomize_questions BOOLEAN DEFAULT FALSE;

-- 4. Add assigned_questions to test_attempts table
ALTER TABLE public.test_attempts ADD COLUMN IF NOT EXISTS assigned_questions JSONB DEFAULT '[]'::jsonb;

-- 5. Enable Row Level Security (RLS) on question_banks
ALTER TABLE public.question_banks ENABLE ROW LEVEL SECURITY;

-- 6. Create public access policy for question_banks
DROP POLICY IF EXISTS "Allow public access question_banks" ON public.question_banks;
CREATE POLICY "Allow public access question_banks" ON public.question_banks FOR ALL USING (true) WITH CHECK (true);

-- 7. Insert default August Month Question Bank for Second Year
INSERT INTO public.question_banks (id, title, description, year, status)
VALUES (1, 'August Month Question Bank', 'August Month Question Bank with 20 seeded coding challenges', 'Second Year', 'Active')
ON CONFLICT (id) DO NOTHING;

-- 8. Place all existing questions inside the August Month Question Bank
UPDATE public.questions SET question_bank_id = 1;
