-- Test-only Testcontainers init script: pre-creates the Supabase-managed
-- roles (anon, authenticated) that supabase_schema.sql's REVOKE statements
-- reference but that don't exist on a plain postgres:17 image. This file
-- is generated by concatenating this prelude with the real
-- supabase_schema.sql (the actual tracked source of truth) -- see
-- AbstractIntegrationTest. Regenerate if supabase_schema.sql changes.

DO $$
BEGIN
  CREATE ROLE anon;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
  CREATE ROLE authenticated;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- ============================================================================
-- CodeArena — Authoritative Supabase schema (single source of truth)
-- Run this file in the Supabase SQL editor. Data seeding is done separately
-- by backend/seed_supabase.py (service role). The FastAPI backend connects
-- with the service-role DATABASE_URL; the frontend never touches this schema.
--
-- RLS: every table has ROW LEVEL SECURITY enabled with access restricted to
-- service_role. The anon role gets NOTHING — no grants, no policies.
-- ============================================================================

-- ────────────────────────────────────────────────────────────────────────────
-- users
-- ────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.users (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email           TEXT UNIQUE NOT NULL,
    register_number TEXT UNIQUE,
    name            TEXT NOT NULL,
    password_hash   TEXT NOT NULL,
    role            TEXT NOT NULL DEFAULT 'student' CHECK (role IN ('admin', 'student')),
    department      TEXT,
    year            INT,
    section         TEXT,
    status          TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'inactive')),
    is_active       BOOLEAN NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ────────────────────────────────────────────────────────────────────────────
-- question_banks
-- ────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.question_banks (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title       TEXT NOT NULL,
    description TEXT,
    year        TEXT NOT NULL DEFAULT 'Second Year',
    status      TEXT NOT NULL DEFAULT 'Active',
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ────────────────────────────────────────────────────────────────────────────
-- questions
-- ────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.questions (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title            TEXT NOT NULL,
    statement        TEXT NOT NULL,
    difficulty       TEXT NOT NULL DEFAULT 'easy' CHECK (difficulty IN ('easy', 'medium', 'hard')),
    marks            INT NOT NULL DEFAULT 10,
    topic            TEXT NOT NULL DEFAULT 'General',
    input_format     TEXT,
    output_format    TEXT,
    constraints      TEXT,
    sample_input     TEXT,
    sample_output    TEXT,
    explanation      TEXT,
    question_bank_id BIGINT REFERENCES public.question_banks(id) ON DELETE SET NULL,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ────────────────────────────────────────────────────────────────────────────
-- test_cases
-- ────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.test_cases (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question_id     BIGINT NOT NULL REFERENCES public.questions(id) ON DELETE CASCADE,
    input           TEXT NOT NULL,
    expected_output TEXT NOT NULL,
    is_hidden       BOOLEAN NOT NULL DEFAULT FALSE,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ────────────────────────────────────────────────────────────────────────────
-- tests
-- ────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.tests (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                  TEXT NOT NULL,
    description           TEXT,
    year                  TEXT NOT NULL DEFAULT 'Second Year',
    question_bank_id      BIGINT REFERENCES public.question_banks(id) ON DELETE SET NULL,
    randomize_questions   BOOLEAN NOT NULL DEFAULT FALSE,
    start_time            TIMESTAMPTZ NOT NULL,
    end_time              TIMESTAMPTZ NOT NULL,
    duration_minutes      INT NOT NULL,
    total_marks           INT NOT NULL,
    questions_per_student INT NOT NULL,
    easy_count            INT NOT NULL DEFAULT 0,
    medium_count          INT NOT NULL DEFAULT 0,
    hard_count            INT NOT NULL DEFAULT 0,
    allowed_languages     JSONB NOT NULL DEFAULT '["python", "java", "c", "cpp"]'::jsonb,
    max_violations        INT NOT NULL DEFAULT 3,
    allow_copy_paste      BOOLEAN NOT NULL DEFAULT FALSE,
    scoring_type          TEXT NOT NULL DEFAULT 'partial' CHECK (scoring_type IN ('partial', 'all_or_nothing')),
    show_results          BOOLEAN NOT NULL DEFAULT FALSE,
    created_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT tests_window_valid CHECK (end_time > start_time)
);

-- ────────────────────────────────────────────────────────────────────────────
-- test_questions (test question pool)
-- ────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.test_questions (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    test_id     BIGINT NOT NULL REFERENCES public.tests(id) ON DELETE CASCADE,
    question_id BIGINT NOT NULL REFERENCES public.questions(id) ON DELETE CASCADE,
    UNIQUE (test_id, question_id)
);

-- ────────────────────────────────────────────────────────────────────────────
-- student_question_assignments — ONE stable question per (student, test)
-- ────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.student_question_assignments (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id  BIGINT NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    test_id     BIGINT NOT NULL REFERENCES public.tests(id) ON DELETE CASCADE,
    question_id BIGINT NOT NULL REFERENCES public.questions(id) ON DELETE CASCADE,
    assigned_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (student_id, test_id)
);

-- ────────────────────────────────────────────────────────────────────────────
-- test_attempts — canonical lifecycle: in_progress → submitted | auto_submitted
-- ────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.test_attempts (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    test_id         BIGINT NOT NULL REFERENCES public.tests(id) ON DELETE CASCADE,
    status          TEXT NOT NULL DEFAULT 'in_progress'
                    CHECK (status IN ('not_started', 'in_progress', 'submitted', 'auto_submitted')),
    started_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    expires_at      TIMESTAMPTZ NOT NULL DEFAULT (NOW() + INTERVAL '1 hour'),
    submitted_at    TIMESTAMPTZ,
    violation_count INT NOT NULL DEFAULT 0,
    score           INT NOT NULL DEFAULT 0,
    UNIQUE (user_id, test_id)
);

-- ────────────────────────────────────────────────────────────────────────────
-- student_questions (per-attempt selection snapshot)
-- ────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.student_questions (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    attempt_id  BIGINT NOT NULL REFERENCES public.test_attempts(id) ON DELETE CASCADE,
    question_id BIGINT NOT NULL REFERENCES public.questions(id) ON DELETE CASCADE,
    position    INT NOT NULL,
    UNIQUE (attempt_id, question_id)
);

-- ────────────────────────────────────────────────────────────────────────────
-- student_code (auto-save drafts)
-- ────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.student_code (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    attempt_id  BIGINT NOT NULL REFERENCES public.test_attempts(id) ON DELETE CASCADE,
    question_id BIGINT NOT NULL REFERENCES public.questions(id) ON DELETE CASCADE,
    language    TEXT NOT NULL DEFAULT 'python',
    source_code TEXT,
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (attempt_id, question_id)
);

-- ────────────────────────────────────────────────────────────────────────────
-- submissions (graded records) + submission_results (per-case detail)
-- ────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.submissions (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    attempt_id        BIGINT NOT NULL REFERENCES public.test_attempts(id) ON DELETE CASCADE,
    question_id       BIGINT NOT NULL REFERENCES public.questions(id) ON DELETE CASCADE,
    language          TEXT NOT NULL DEFAULT 'python',
    code              TEXT NOT NULL,
    status            TEXT,
    score             FLOAT NOT NULL DEFAULT 0,
    total_test_cases  INT NOT NULL DEFAULT 0,
    passed_test_cases INT NOT NULL DEFAULT 0,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.submission_results (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    submission_id  BIGINT NOT NULL REFERENCES public.submissions(id) ON DELETE CASCADE,
    test_case_id   BIGINT,
    passed         BOOLEAN NOT NULL DEFAULT FALSE,
    output         TEXT,
    execution_time FLOAT,
    memory_used    INT,
    status         TEXT
);

-- ────────────────────────────────────────────────────────────────────────────
-- violations
-- ────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.violations (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    attempt_id     BIGINT NOT NULL REFERENCES public.test_attempts(id) ON DELETE CASCADE,
    violation_type TEXT NOT NULL,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ============================================================================
-- Row Level Security — service_role only. The backend connects as service
-- role (bypasses RLS); anon/authenticated are locked out completely.
-- ============================================================================
ALTER TABLE public.users                      ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.question_banks             ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.questions                  ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.test_cases                 ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tests                      ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.test_questions             ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.student_question_assignments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.test_attempts              ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.student_questions          ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.student_code               ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.submissions                ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.submission_results         ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.violations                 ENABLE ROW LEVEL SECURITY;

-- service_role bypasses RLS by default; revoke anything granted to anon.
REVOKE ALL ON ALL TABLES IN SCHEMA public FROM anon;
REVOKE ALL ON ALL SEQUENCES IN SCHEMA public FROM anon;
REVOKE ALL ON ALL TABLES IN SCHEMA public FROM authenticated;
REVOKE ALL ON ALL SEQUENCES IN SCHEMA public FROM authenticated;

-- ============================================================================
-- Migration for EXISTING deployments created before this schema version
-- (idempotent; safe to run alongside the CREATE TABLE statements above).
-- ============================================================================
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS email TEXT;
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS password_hash TEXT;
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS status TEXT NOT NULL DEFAULT 'active';
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS is_active BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();

ALTER TABLE public.questions ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();
ALTER TABLE public.question_banks ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();
ALTER TABLE public.tests ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT NOW();
ALTER TABLE public.tests ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();
ALTER TABLE public.test_cases ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT NOW();

-- test_attempts must guarantee exactly one attempt per (user, test).
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'uq_user_test'
    ) THEN
        ALTER TABLE public.test_attempts ADD CONSTRAINT uq_user_test UNIQUE (user_id, test_id);
    END IF;
END $$;
